//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.28 at 11:30:00 AM CET 
//

package MenegazziCotroneo.Ordini.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Classe Java per rappresentare una lista di utenti.</p>
 * 
 * <p>Il seguente frammento XML mostra la struttura prevista:</p>
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="utente" type="{}Utente" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "utente"
})
@XmlRootElement(name = "utenti")
public class Utenti {

    @XmlElement(name = "utente")
    protected List<Utente> utente;

    /**
     * Restituisce la lista degli utenti.
     * 
     * <p>
     * Questo metodo restituisce un riferimento alla lista effettiva,
     * quindi qualsiasi modifica si rifletterà nell'oggetto XML.
     * 
     * <p>
     * Per esempio, per aggiungere un nuovo utente:
     * <pre>
     *    getUtente().add(new Utente());
     * </pre>
     * 
     * <p>
     * Oggetti di tipo {@link Utente} sono consentiti nella lista.
     * 
     * @return lista di utenti
     */
    public List<Utente> getUtente() {
        if (utente == null) {
            utente = new ArrayList<Utente>();
        }
        return this.utente;
    }
}
