//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 06:46:16 PM CET 
//

package app.model.xml;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * Questa classe contiene metodi factory per ogni 
 * interfaccia di contenuto XML e interfaccia elemento XML 
 * generata nel package app.model.ordini.
 * <p>Un ObjectFactory consente di creare programmaticamente 
 * nuove istanze della rappresentazione Java per il contenuto XML.
 * La rappresentazione Java del contenuto XML può consistere in 
 * interfacce derivate dallo schema e classi che rappresentano 
 * il binding delle definizioni di tipo, dichiarazioni di elementi 
 * e gruppi di modelli dello schema.
 * <p>Questa classe fornisce metodi factory per ogni classe generata.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Crea un nuovo ObjectFactory utilizzabile per creare nuove istanze 
     * delle classi derivate dallo schema per il package: app.model.ordini
     */
    public ObjectFactory() {
    }

    /**
     * Crea un'istanza di {@link Ordini}
     * 
     */
    public Ordini createOrdini() {
        return new Ordini();
    }

    /**
     * Crea un'istanza di {@link Ordine}
     * 
     */
    public Ordine createOrdine() {
        return new Ordine();
    }
}
